export enum Transactions {
  INCOMING_TRANSACTION = 'INCOMING_TRANSACTION',
  OUTGOING_TRANSACTION = 'OUTGOING_TRANSACTION',
  ADDRESSES_RESPONSE = 'ADDRESSES_RESPONSE',
  ADDRESSES_REQUEST = 'ADDRESSES_REQUEST'
}
